name: New Relic Synthetics

# -------------------------------------------------------------------------------------------------------------------------
# Event `push`: Compare the preceding commit -> to the current commit.
# -------------------------------------------------------------------------------------------------------------------------
on: [push]

env:
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }} #Required repository secret

jobs:
  sync_synthetic_monitors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      # Detects changes to .js files only in any sub path, formats those filenames/paths as json
      - name: Get Changed Scripts
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: ","
          files: |    # Modify this to wherever your specific scripts reside - defaults to any js files
            **/*.js
          json: "true"

      # Proceed with storing filenames/paths in a local file for further processing, ONLY if any .js files have changed or been committed.
      - name: Store Changed Scripts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }} > monitors.json
          cat monitors.json

      # Parse out js filenames, which should match the entity names within NR, fetch the entity's guid, and update existing monitor or create new one
      - name: Sync Changes to Synthetics
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: newrelic-experimental/synthetics-sync@v1.2
        with: # all optional defaults for creation of new scripts committed
          accountId: 6776469
          runtime: "new"
          privateLocations: ""
          publicLocations: "['AWS_US_EAST_1']"
          interval: EVERY_15_MINUTES
          status: ENABLED
          monitorType: SCRIPT_BROWSER
